audit_header: false
title: "Myrtle Beach's Best Real Estate Agent Training"
description: Scott Trembley, a top Real Estate Agent in Myrtle Beach, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: Events
    url: https://www.eventbrite.com/o/the-trembley-group-real-estate-18006975621
  - title: About Us
    url: /about/


client:
  name: Scott Trembley
  title:
  license_number:
  about_markdown: |
    The Trembley Group is not your average Real Estate firm. The environment we create provides everything you will need to succeed: consistent training, marketing/ administrative support, an abundance of leads, and a proven system for sales success.

    <strong>Our commitment is to assist real estate sales executives in creating a more predictable business and balanced life.</strong>

    The Trembley Group was established by seasoned, award-winning professionals who are passionate about real estate.  We specialize in positively changing lives one relationship at a time. Our impact is achieved through consistent communication and collaboration, innovative services and a vast knowledge of today’s Real Estate market.  Our group culture is fostered through powerful principles, hard work, faith, honesty, and a daily commitment to excellence. We are leaders looking to collaborate and experience business growth with other like-minded leaders.  Our CORE VALUES are super important to us around here. They drive us daily!
  market: Myrtle Beach
  brand: The Trembley Group Real Estate
  brokerage:
  address: 1101 Johnson Avenue, Suite 104<br>Myrtle Beach, SC 29577
  phone: 843-455-6636
  phone_type:
  phone2:
  phone2_type:
  email: Scott@TheTrembleyGroup.com
  url: http://JoinTTG.com
  url2: http://TheTrembleyGroup.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/The-Trembley-Groups-Elite-Mastermind-293710074797074/
  linkedin_url: https://www.linkedin.com/in/scotttrembley/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCMnQc8rkBHxVIsxTJfc4NXw
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Myrtle Beach Real Estate Training Podcast with Scott Trembley'
  categories: Education
  image: /img/trembley_podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#016eb1'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
